# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Article.destroy_all
Article.create(tile:"Improve your CV", author:"Thomas BG", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus cursus dui sem, et aliquet purus elementum at. Nam gravida, turpis et finibus gravida, neque nunc rhoncus nisl, nec vestibulum sem urna eget urna. Donec quis risus eleifend, ultricies augue non, finibus tellus. Pellentesque in justo non arcu consectetur pulvinar. Quisque ornare justo nec dui efficitur auctor. Ut quis justo mi. Donec tincidunt bibendum egestas. Integer convallis nunc tellus, ac faucibus diam tristique in. Sed molestie lorem molestie congue volutpat. Morbi ut sapien ac leo feugiat ornare. Praesent dapibus erat non fringilla accumsan. Etiam quam mi, ornare eu nisl at, hendrerit fermentum odio. Cras lorem augue, aliquet aliquet posuere et, lobortis sed sapien. Vivamus vehicula tellus non eros blandit congue. In nisl orci, viverra at mi eget, ultricies venenatis nisi.

Aliquam ornare eros non nibh aliquet mattis. Duis eu urna nec nunc mollis sagittis. Sed pulvinar elit sed augue molestie ultrices. Curabitur nunc mi, ornare ut lacus vel, porttitor accumsan libero. Quisque ullamcorper eget metus at interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla quis massa gravida, venenatis odio ut, pretium dui. Phasellus a fermentum nibh.

Etiam dapibus arcu sit amet lorem maximus, sit amet ornare enim dictum. Nullam vitae pretium est, sed tempor tortor. Proin eleifend, mauris ac tincidunt pharetra, dui velit ultrices felis, ac condimentum mi risus in ante. Integer sit amet faucibus leo, a faucibus tellus. Praesent tempor orci et massa euismod, in finibus nisl efficitur. Vivamus sed elit nibh. Sed non lorem laoreet, rutrum odio eget, gravida enim.

Nunc ac feugiat felis. Quisque eget malesuada odio, vitae tempor nulla. Integer finibus tellus suscipit, accumsan ligula ac, hendrerit dolor. Donec iaculis vulputate rhoncus. Aliquam feugiat leo eget libero placerat, eget consequat enim pulvinar. Fusce vel dolor neque. Donec hendrerit et justo sit amet tincidunt. Donec bibendum faucibus tincidunt. Sed efficitur ornare est, vitae dapibus mauris placerat sit amet. Sed dictum est imperdiet magna semper tristique. Aliquam gravida justo ipsum, et consectetur lorem malesuada eget. Donec pellentesque lectus vitae diam semper fermentum.

Phasellus in leo dignissim, pretium quam nec, pellentesque turpis. Phasellus quis pellentesque ex, ut pellentesque nisl. Sed aliquet tincidunt nulla, a feugiat libero finibus vitae. Proin a ex et odio aliquet dignissim. Phasellus accumsan tempor massa, quis scelerisque dolor faucibus vel. Pellentesque fringilla, eros ut iaculis euismod, justo massa egestas lacus, tempor efficitur mauris mauris nec mauris. Vestibulum ac orci a velit faucibus egestas. Donec maximus nisi laoreet, molestie purus non, lobortis dui. Praesent dictum rutrum lorem id viverra.")


Article.create(tile:"Do a motivation letter", author:"Maxou chaton", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus cursus dui sem, et aliquet purus elementum at. Nam gravida, turpis et finibus gravida, neque nunc rhoncus nisl, nec vestibulum sem urna eget urna. Donec quis risus eleifend, ultricies augue non, finibus tellus. Pellentesque in justo non arcu consectetur pulvinar. Quisque ornare justo nec dui efficitur auctor. Ut quis justo mi. Donec tincidunt bibendum egestas. Integer convallis nunc tellus, ac faucibus diam tristique in. Sed molestie lorem molestie congue volutpat. Morbi ut sapien ac leo feugiat ornare. Praesent dapibus erat non fringilla accumsan. Etiam quam mi, ornare eu nisl at, hendrerit fermentum odio. Cras lorem augue, aliquet aliquet posuere et, lobortis sed sapien. Vivamus vehicula tellus non eros blandit congue. In nisl orci, viverra at mi eget, ultricies venenatis nisi.

Aliquam ornare eros non nibh aliquet mattis. Duis eu urna nec nunc mollis sagittis. Sed pulvinar elit sed augue molestie ultrices. Curabitur nunc mi, ornare ut lacus vel, porttitor accumsan libero. Quisque ullamcorper eget metus at interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla quis massa gravida, venenatis odio ut, pretium dui. Phasellus a fermentum nibh.

Etiam dapibus arcu sit amet lorem maximus, sit amet ornare enim dictum. Nullam vitae pretium est, sed tempor tortor. Proin eleifend, mauris ac tincidunt pharetra, dui velit ultrices felis, ac condimentum mi risus in ante. Integer sit amet faucibus leo, a faucibus tellus. Praesent tempor orci et massa euismod, in finibus nisl efficitur. Vivamus sed elit nibh. Sed non lorem laoreet, rutrum odio eget, gravida enim.

Nunc ac feugiat felis. Quisque eget malesuada odio, vitae tempor nulla. Integer finibus tellus suscipit, accumsan ligula ac, hendrerit dolor. Donec iaculis vulputate rhoncus. Aliquam feugiat leo eget libero placerat, eget consequat enim pulvinar. Fusce vel dolor neque. Donec hendrerit et justo sit amet tincidunt. Donec bibendum faucibus tincidunt. Sed efficitur ornare est, vitae dapibus mauris placerat sit amet. Sed dictum est imperdiet magna semper tristique. Aliquam gravida justo ipsum, et consectetur lorem malesuada eget. Donec pellentesque lectus vitae diam semper fermentum.

Phasellus in leo dignissim, pretium quam nec, pellentesque turpis. Phasellus quis pellentesque ex, ut pellentesque nisl. Sed aliquet tincidunt nulla, a feugiat libero finibus vitae. Proin a ex et odio aliquet dignissim. Phasellus accumsan tempor massa, quis scelerisque dolor faucibus vel. Pellentesque fringilla, eros ut iaculis euismod, justo massa egestas lacus, tempor efficitur mauris mauris nec mauris. Vestibulum ac orci a velit faucibus egestas. Donec maximus nisi laoreet, molestie purus non, lobortis dui. Praesent dictum rutrum lorem id viverra.")


Article.create(tile:"Negotiate salary", author:"Grégui", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus cursus dui sem, et aliquet purus elementum at. Nam gravida, turpis et finibus gravida, neque nunc rhoncus nisl, nec vestibulum sem urna eget urna. Donec quis risus eleifend, ultricies augue non, finibus tellus. Pellentesque in justo non arcu consectetur pulvinar. Quisque ornare justo nec dui efficitur auctor. Ut quis justo mi. Donec tincidunt bibendum egestas. Integer convallis nunc tellus, ac faucibus diam tristique in. Sed molestie lorem molestie congue volutpat. Morbi ut sapien ac leo feugiat ornare. Praesent dapibus erat non fringilla accumsan. Etiam quam mi, ornare eu nisl at, hendrerit fermentum odio. Cras lorem augue, aliquet aliquet posuere et, lobortis sed sapien. Vivamus vehicula tellus non eros blandit congue. In nisl orci, viverra at mi eget, ultricies venenatis nisi.

Aliquam ornare eros non nibh aliquet mattis. Duis eu urna nec nunc mollis sagittis. Sed pulvinar elit sed augue molestie ultrices. Curabitur nunc mi, ornare ut lacus vel, porttitor accumsan libero. Quisque ullamcorper eget metus at interdum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla quis massa gravida, venenatis odio ut, pretium dui. Phasellus a fermentum nibh.

Etiam dapibus arcu sit amet lorem maximus, sit amet ornare enim dictum. Nullam vitae pretium est, sed tempor tortor. Proin eleifend, mauris ac tincidunt pharetra, dui velit ultrices felis, ac condimentum mi risus in ante. Integer sit amet faucibus leo, a faucibus tellus. Praesent tempor orci et massa euismod, in finibus nisl efficitur. Vivamus sed elit nibh. Sed non lorem laoreet, rutrum odio eget, gravida enim.

Nunc ac feugiat felis. Quisque eget malesuada odio, vitae tempor nulla. Integer finibus tellus suscipit, accumsan ligula ac, hendrerit dolor. Donec iaculis vulputate rhoncus. Aliquam feugiat leo eget libero placerat, eget consequat enim pulvinar. Fusce vel dolor neque. Donec hendrerit et justo sit amet tincidunt. Donec bibendum faucibus tincidunt. Sed efficitur ornare est, vitae dapibus mauris placerat sit amet. Sed dictum est imperdiet magna semper tristique. Aliquam gravida justo ipsum, et consectetur lorem malesuada eget. Donec pellentesque lectus vitae diam semper fermentum.

Phasellus in leo dignissim, pretium quam nec, pellentesque turpis. Phasellus quis pellentesque ex, ut pellentesque nisl. Sed aliquet tincidunt nulla, a feugiat libero finibus vitae. Proin a ex et odio aliquet dignissim. Phasellus accumsan tempor massa, quis scelerisque dolor faucibus vel. Pellentesque fringilla, eros ut iaculis euismod, justo massa egestas lacus, tempor efficitur mauris mauris nec mauris. Vestibulum ac orci a velit faucibus egestas. Donec maximus nisi laoreet, molestie purus non, lobortis dui. Praesent dictum rutrum lorem id viverra.")
